### ISSUE TITLE
Incompatible with Wagtail >=2.2

### ISSUE THREAD

**Issue by stefan-squareweave** [takeflight/wagtailmodelchooser#13]
The internal Wagtail functionality used by this package [has changed its API](http://docs.wagtail.io/en/v2.2/releases/2.2.html#javascript-templates-in-modal-workflows-are-deprecated) and so this package doesn't work on Wagtail >=2.2.

Specifically, when you press the 'Choose \<entity\>' button in Wagtail admin you'll get a stacktrace like this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtailmodelchooser/views.py", line 86, in chooser
    context)
  File "/usr/local/lib/python3.6/site-packages/wagtail/admin/modal_workflow.py", line 11, in render_modal_workflow
    raise TypeError("Passing a js_template argument to render_modal_workflow is no longer supported")
TypeError: Passing a js_template argument to render_modal_workflow is no longer supported
```

The only way to be backwards compatible is to do version sniffing I think and to maintain two versions of the JS. As such I think the solution will be to make a new major version of wagtailmodelchooser which supports Wagtail >=2.2.

I'm going to fork this repo to fix the issue for my project and will then link to a PR here.

**Comment by pierremanceaux** [comment]
Yeah, I confirm that is it broken on our end too. Thanks for the PR!

**Comment by brianedelman** [comment]
+1

**Comment by seb-b** [comment]
Should be good in newest release, 2.2.0
